Script started on 2021-02-04 13:20:13-06:00
]777;notify;Command completed;ls]0;gemerson@localhost:/home/gemerson/cs161]7;file://localhost.localdomain/home/gemerson/cs161[root@localhost cs161]# mkdir asst0
]777;notify;Command completed;mkdir asst0]0;gemerson@localhost:/home/gemerson/cs161]7;file://localhost.localdomain/home/gemerson/cs161[root@localhost cs161]# ls
[0m[38;5;33masst0[0m               [38;5;33mcs161-gcc-1.5[0m  [38;5;33mos161-1.10[0m    [38;5;33msys161-1.14[0m
[38;5;33mcs161-binutils-1.5[0m  [38;5;33mcs161-gdb-1.5[0m  setup.script  sys161.conf
]777;notify;Command completed;ls]0;gemerson@localhost:/home/gemerson/cs161]7;file://localhost.localdomain/home/gemerson/cs161[root@localhost cs161]# mv os161-1.10 os161
]777;notify;Command completed;mv os161-1.10 os161]0;gemerson@localhost:/home/gemerson/cs161]7;file://localhost.localdomain/home/gemerson/cs161[root@localhost cs161]# ls
[0m[38;5;33masst0[0m               [38;5;33mcs161-gcc-1.5[0m  [38;5;33mos161[0m         [38;5;33msys161-1.14[0m
[38;5;33mcs161-binutils-1.5[0m  [38;5;33mcs161-gdb-1.5[0m  setup.script  sys161.conf
]777;notify;Command completed;ls]0;gemerson@localhost:/home/gemerson/cs161]7;file://localhost.localdomain/home/gemerson/cs161[root@localhost cs161]# exit
exit

Script done on 2021-02-04 13:22:52-06:00
